'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {World}=require('./engine.js');const rooms=new Map(),sessions=new Map(),PORT=Number(process.env.PORT)||8787;
function reply(res,n,obj){res.writeHead(n,{'Content-Type':typeof obj==='string'?'text/plain; charset=utf-8':'application/json','Cache-Control':'no-store'});res.end(typeof obj==='string'?obj:JSON.stringify(obj))}
function remove(id){let s=sessions.get(id);if(!s)return;if(s.res)s.res.end();s.room.world.players=s.room.world.players.filter(p=>p.id!==id);sessions.delete(id)}
const server=http.createServer(async(req,res)=>{let u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(path.join(__dirname,'CHOI-NGAY.html')))}
if(req.method==='GET'&&u.pathname==='/health')return reply(res,200,{ok:true,version:'1.8',players:sessions.size,rooms:rooms.size});
if(req.method==='GET'&&u.pathname==='/status')return reply(res,200,{version:'1.8',players:sessions.size,rooms:[...rooms.entries()].map(([code,r])=>({code,players:r.world.players.filter(p=>!p.bot).length}))});
if(req.method==='GET'&&u.pathname==='/Mischief_in_the_Moss.mp3'){let f=path.join(__dirname,'Mischief_in_the_Moss.mp3');res.writeHead(200,{'Content-Type':'audio/mpeg','Cache-Control':'public, max-age=3600'});return fs.createReadStream(f).pipe(res)}
if(req.method==='GET'&&u.pathname==='/events'){let s=sessions.get(u.searchParams.get('id'));if(!s)return reply(res,404,'Phiên không tồn tại');if(s.res)s.res.end();res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(': connected\n\n');s.res=res;s.seen=Date.now();req.on('close',()=>{if(s.res===res)s.res=null});return}
if(req.method!=='POST')return reply(res,404,'Không tìm thấy');let origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)return reply(res,403,'Nguồn không hợp lệ');let chunks=[],size=0;try{for await(let c of req){size+=c.length;if(size>4096){reply(res,413,'Yêu cầu quá lớn');return}chunks.push(c)}let data=JSON.parse(Buffer.concat(chunks).toString()||'{}');if(u.pathname==='/join'){if(sessions.size>=120)return reply(res,429,'Máy chủ đã đầy');let code=String(data.room||'CONGTY').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20)||'CONGTY';if(!rooms.has(code)){if(rooms.size>=8)return reply(res,429,'Đã đủ phòng');rooms.set(code,{world:new World([16,24,30].includes(data.count)?data.count:24),empty:Date.now()})}let room=rooms.get(code);if(room.world.players.filter(p=>!p.bot).length>=30)return reply(res,409,'Phòng đủ 30 người');let id=crypto.randomBytes(18).toString('hex');room.world.join(data.name,Number.isInteger(data.species)&&data.species>=0&&data.species<15?data.species:0,id);sessions.set(id,{room,seen:Date.now(),res:null,lastInput:0});return reply(res,200,{id,room:code})}
let s=sessions.get(data.id);if(!s)return reply(res,404,'Phiên đã hết');if(u.pathname==='/leave'){remove(data.id);return reply(res,200,{ok:true})}if(u.pathname==='/input'){let now=Date.now();if(now-s.lastInput<20)return reply(res,429,'Quá nhanh');s.lastInput=now;s.seen=now;let p=s.room.world.players.find(p=>p.id===data.id);p.input={x:Number.isFinite(data.x)?Math.max(-1,Math.min(1,data.x)):0,y:Number.isFinite(data.y)?Math.max(-1,Math.min(1,data.y)):0,l:!!data.l,r:!!data.r,e:!!data.e||!!p.input.e,tap:!!data.tap||!!p.input.tap};return reply(res,200,{ok:true})}return reply(res,404,'Không tìm thấy')}catch(e){reply(res,400,'Dữ liệu không hợp lệ')}});
let ticks=0;setInterval(()=>{for(let [id,s]of sessions){if(Date.now()-s.seen>30000){remove(id);continue}if(Date.now()-s.seen>600){let p=s.room.world.players.find(p=>p.id===id);if(p)p.input={x:0,y:0,l:false,r:false}}}for(let [code,r]of rooms){if(!r.world.players.some(p=>!p.bot)){if(Date.now()-r.empty>30000){rooms.delete(code);continue}}else r.empty=Date.now();r.world.step(1/30)}if(++ticks%3===0)for(let [id,s]of sessions)if(s.res&&!s.res.destroyed&&s.res.writableLength<150000)s.res.write('data: '+JSON.stringify(s.room.world.snapshot(id))+'\n\n')},1000/30);
server.listen(PORT,'0.0.0.0',()=>{
console.log(`WILDWOOD 1.8 ONLINE READY · port ${PORT}`);
console.log(`Health check: /health`);
});
function shutdown(){console.log('Dang tat Wildwood server...');for(let [id] of sessions)remove(id);server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),4000).unref()}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
server.on('error',e=>{console.error('Server error: '+e.message);process.exit(1)});
