'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {WebSocketServer}=require('ws');const {World}=require('./engine.js');
const rooms=new Map(),sessions=new Map(),PORT=Number(process.env.PORT)||8787;
function reply(res,n,o){res.writeHead(n,{'Content-Type':typeof o==='string'?'text/plain; charset=utf-8':'application/json','Cache-Control':'no-store'});res.end(typeof o==='string'?o:JSON.stringify(o))}
function remove(id){let s=sessions.get(id);if(!s)return;s.room.world.players=s.room.world.players.filter(p=>p.id!==id);sessions.delete(id)}
function join(d,ws){if(sessions.size>=120)throw Error('Máy chủ đã đầy');let code=String(d.room||'WORLD1').toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20)||'WORLD1';if(!rooms.has(code))rooms.set(code,{world:new World([16,24,30].includes(d.count)?d.count:24),empty:Date.now()});let room=rooms.get(code);if(room.world.players.filter(p=>!p.bot).length>=30)throw Error('Phòng đầy');let id=crypto.randomBytes(18).toString('hex');room.world.join(String(d.name||'Khách').slice(0,18),Number.isInteger(d.species)&&d.species>=0&&d.species<15?d.species:0,id);sessions.set(id,{room,ws,seen:Date.now(),seq:0});return{id,room:code}}
function input(s,d){s.seen=Date.now();s.seq=d.seq||s.seq;let p=s.room.world.players.find(p=>p.id===d.id);if(p)p.input={x:Number.isFinite(d.x)?Math.max(-1,Math.min(1,d.x)):0,y:Number.isFinite(d.y)?Math.max(-1,Math.min(1,d.y)):0,l:!!d.l,r:!!d.r,e:!!d.e||!!p.input.e,tap:!!d.tap||!!p.input.tap}}
const server=http.createServer((req,res)=>{let u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/') {res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(path.join(__dirname,'CHOI-NGAY.html')))}if(u.pathname==='/health')return reply(res,200,{ok:true,version:'1.10',transport:'websocket',players:sessions.size,rooms:rooms.size});if(u.pathname==='/status')return reply(res,200,{version:'1.10',players:sessions.size});if(u.pathname==='/Mischief_in_the_Moss.mp3'){res.writeHead(200,{'Content-Type':'audio/mpeg','Cache-Control':'public,max-age=3600'});return fs.createReadStream(path.join(__dirname,'Mischief_in_the_Moss.mp3')).pipe(res)}reply(res,404,'Không tìm thấy')});
const wss=new WebSocketServer({server,path:'/ws',perMessageDeflate:false,maxPayload:4096});
wss.on('connection',ws=>{let sid=null;ws.isAlive=true;ws.on('pong',()=>ws.isAlive=true);ws.on('message',b=>{try{let d=JSON.parse(b);if(d.type==='join'&&!sid){let j=join(d,ws);sid=j.id;return ws.send(JSON.stringify({type:'joined',...j}))}if(!sid)return;let s=sessions.get(sid);if(!s)return;if(d.type==='input'){d.id=sid;input(s,d)}else if(d.type==='leave'){remove(sid);sid=null}}catch(e){try{ws.send(JSON.stringify({type:'error',message:e.message}))}catch{}}});ws.on('close',()=>{if(sid)remove(sid)});ws.on('error',()=>{})});
let ticks=0;setInterval(()=>{let now=Date.now();for(let[id,s]of sessions){if(now-s.seen>30000){remove(id);continue}if(now-s.seen>1000){let p=s.room.world.players.find(p=>p.id===id);if(p)p.input={x:0,y:0,l:false,r:false}}}for(let[code,r]of rooms){if(!r.world.players.some(p=>!p.bot)){if(now-r.empty>30000){rooms.delete(code);continue}}else r.empty=now;r.world.step(1/30)}if(++ticks%2===0)for(let[id,s]of sessions)if(s.ws?.readyState===1&&s.ws.bufferedAmount<120000)s.ws.send(JSON.stringify({type:'state',ack:s.seq,state:s.room.world.snapshot(id)}))},1000/30);
setInterval(()=>{for(let ws of wss.clients){if(ws.isAlive===false){ws.terminate();continue}ws.isAlive=false;try{ws.ping()}catch{}}},10000);
server.listen(PORT,'0.0.0.0',()=>console.log('WILDWOOD 1.10 WebSocket · '+PORT));process.on('SIGTERM',()=>server.close(()=>process.exit()));process.on('SIGINT',()=>server.close(()=>process.exit()));
